### ISSUE TITLE
How to change the datasets to train monet?

### ISSUE THREAD

**Issue by HymEric** [baudm/MONet-pytorch#7]
I want to use my own datasets to train Monet? Could you give me some suggestions?  So appreciated!

**Comment by baudm** [comment]
Take a look at `SingleDataset` in `https://github.com/baudm/MONet-pytorch/blob/master/data/single_dataset.py`
You can use it as-is as long as your image transform requirement is covered by the `get_transform()` function.
I created a new class, `CLEVRDataset`, because the `get_transform()` function can't achieve the specific image transformations that are needed for CLEVR.

**Comment by baudm** [comment]
Also, check out the options via `./train.py --help`

**Comment by HymEric** [comment]
Thanks a lot. I'm doing my datasets. Must the input images be 64x64?  Can I change the input size of images?

**Comment by baudm** [comment]
The current implementation currently accepts 64x64 or 128x128. You can use 128x128 images by passing `full_res=True` to [`ComponentVAE`](https://github.com/baudm/MONet-pytorch/blob/master/models/monet_model.py#L51).

If you want to use other image sizes, you need to specify the correct [number of hidden units in the `nn.Linear` layer](https://github.com/baudm/MONet-pytorch/blob/master/models/networks.py#L632) of `ComponentVAE` to accommodate the change in the feature map dimensions.

**Comment by baudm** [comment]
I forgot-- to use 128x128 images, you also need to uncomment the commented out `AttentionBlock`s in the [`Attention` model](https://github.com/baudm/MONet-pytorch/blob/master/models/networks.py#L749). To use other image sizes, you need to fiddle with with the `Attention` model because it contains `nn.Linear` layers too.

**Comment by HymEric** [comment]
OK. It's really a great work. And can you explain how to get the result of Figure 5 in your paper as you say "single latent z_k,i is traversed from -1.0 to +1.0" 3.2 in disentangled representations?

**Comment by baudm** [comment]
Sorry, but I'm not one of the authors. Better to contact the corresponding author indicated in the paper.

**Comment by HymEric** [comment]
Ok. Thank you very much.
